djangospinner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  path('collections/', views.collections_index, name='collections_index'),
  path('collections/<int:collection_id>/', views.collections_detail, name='collections_detail'),
  path('collections/<int:collection_id>/add_content/', views.add_content, name='add_content'),
  path('collections/<int:collection_id>/delete_content/<int:content_id>/', views.delete_content, name='delete_content'),
  path('collections/create/', views.CollectionCreate.as_view(), name='collections_create'),
  path('collections/<int:pk>/delete/', views.CollectionDelete.as_view(), name='collections_delete'),
  path('accounts/signup/', views.signup, name='signup'),
]

moviespinner/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class ContentCollection(models.Model):
  name = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  
  def __str__(self):
    return self.name
  
  def get_absolute_url(self):
    return reverse("collections_detail", kwargs={"collection_id": self.id})
  
class Content(models.Model):
  name = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  collection = models.ForeignKey(ContentCollection, on_delete=models.CASCADE)
  
  def __str__(self):
    return f'{self.name} - {self.description}'
  
  

main_app/forms.py
from django.forms import ModelForm
from .models import Content

class ContentForm(ModelForm):
  class Meta:
    model = Content
    fields = ['name', 'description']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import serializers
from .models import ContentCollection, Content
from .forms import ContentForm

class Home(LoginView):
  template_name = 'home.html'

def about(request):
  return render(request, 'about.html')

@login_required
def collections_index(request):
  content_collection = ContentCollection.objects.filter(user=request.user)
  return render(request, 'collections/index.html', {'collections':content_collection})

def collections_detail(request, collection_id):
  collection = ContentCollection.objects.get(id=collection_id)
  content = Content.objects.filter(collection=collection_id)
  content_json = serializers.serialize('json', content)
  content_form = ContentForm()
  return render(request, 'collections/detail.html', { 'collection': collection, 'content_form': content_form, 'content': content_json })

def add_content(request, collection_id):
  form = ContentForm(request.POST)
  if form.is_valid():
    new_content= form.save(commit=False)
    new_content.collection_id = collection_id
    new_content.save()
  return redirect('collections_detail', collection_id=collection_id)

def delete_content(request, collection_id, content_id):
  content = Content.objects.get(id=content_id)
  content.delete()
  return redirect('collections_detail', collection_id=collection_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('collections_index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)

class CollectionCreate(LoginRequiredMixin,CreateView):
  model = ContentCollection
  fields = ['name', 'description']
  
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)
  
class CollectionDelete(LoginRequiredMixin,DeleteView):
  model = ContentCollection
  success_url = '/collections/'

main_app/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}"/>
{% endblock %}

{% block content %}
<div class="about-box">
  <h1>About Django Spinner</h1>
  <hr />
  <p class="page-content">
    Originally intended to work alongside a Movie API. Users would be able to select movies or entire categories and put into a collection. Then use a spinner to randomly select one.
  
    Current iteration allows for any type of content in the collection and perform a spinner
  </p>
</div>


{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
  rel="shortcut icon"
  type="image/png"
  href="{% static 'images/wheel.svg' %}"
>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  <title>Django Spinner</title>
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'collections_index'%}">All Collection</a></li>
          <li><a href="{% url 'collections_create' %}">Create Collection</a></li>
          <li><a href="{% url 'logout' %}">Log out</a></li>
        {% else %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/collections/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/collections/collection-detail.css' %}"
/>
<script src='../../static/js/Winwheel.js'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/gsap.min.js"></script>
{% endblock %}

{% block content %}

<section class="detail-header">
  <h1>{{collection.name}}</h1>
  <h3>{{collection.description}}</h3>
</section>

<div class="collection-container">
  <section class="content-add-container">
    <div class="add-content">
      <form
      action="{% url 'add_content' collection.id %}"
      method="post" 
      class="subsection-content"
    >
      {% csrf_token %}
      {{ content_form.as_p }}
      <button type="submit" class="btn submit add-button">Add Content</button>
    </form>
    </div>
    <div class="content-container">
      {% if collection.content_set.all.count != 0 %}
        {% for content in collection.content_set.all %}
        <div class="card">
          <div class="card-content">
            <h2 class="card-title">{{ content.name }}</h2>
            <p><small>{{ content.description }}</small></p>
            <div class="content-actions">
              <a href="{% url 'delete_content' collection.id content.id %}" class="btn danger delete-button">Delete</a>
            </div>
          </div>
        </div>
        {% endfor %}
      {% else %}
        <div>
          <p>There are currently no content. Add some!</p>
        </div>
      {% endif %}
    </div>
  
  </section>

  <section class="spinner-container">
    <div class="canvas-container">
      {% if collection.content_set.all.count != 0 %}
        <canvas id='canvas' width='900' height='400'>
          Canvas not supported, use another browser.
        </canvas>
        <img id="prize-pointer" src="{% static 'images/down-arrow.svg' %}" alt="V">
      {% else %}
      <canvas id='canvas' width='900' height='400'>
        Canvas not supported, use another browser.
      </canvas>
      <img id="prize-pointer" src="{% static 'images/down-arrow.svg' %}" alt="V">
      <script type="text/javascript">
        let theWheel = new Winwheel({
            'canvasId'    : 'canvas',
            'numSegments' : 1,
            'pointerAngle' :0,
            'fillStyle'   : '#e7706f',
            'lineWidth'   : 3,
            'animation'   :
            {
              'type'     : 'spinToStop',  // Type of animation.
              'duration' : 5,             // How long the animation is to take in seconds.
              'spins'    : 8,              // The number of complete 360 degree rotations the wheel is to do.
              'callbackFinished' : 'alertWinner()',
            }
        });
      </script>
      {% endif %}
    </div>
    
    <script type="text/javascript">
        let theWheel = new Winwheel({
            'canvasId'    : 'canvas',
            'numSegments' : 0,
            'pointerAngle' :0,
            'fillStyle'   : '#e7706f',
            'lineWidth'   : 3,
            'animation'   :
            {
              'type'     : 'spinToStop',  // Type of animation.
              'duration' : 5,             // How long the animation is to take in seconds.
              'spins'    : 8,              // The number of complete 360 degree rotations the wheel is to do.
              'callbackFinished' : 'alertWinner()',
            }
        });

        const contentArray = {{content|safe}}
        console.log(contentArray)
        for (let i = 0; i < contentArray.length; i++ ){
          var randomColor = Math.floor(Math.random()*16777215).toString(16);
          const color = hexToRgb(randomColor)
          theWheel.addSegment({
            'text': contentArray[i].fields.name,
            'fillStyle': `rgba(${color.r},${color.g},${color.b},0.5)`,
          })
          theWheel.draw();
        }

        function alertWinner(){
          let winningSegmentNumber = theWheel.getIndicatedSegmentNumber();
          let winningSegment = theWheel.getIndicatedSegment();

          theWheel.segments[winningSegmentNumber].textStrokeStyle = 'yellow';
          theWheel.draw()
          theWheel.rotationAngle = theWheel.rotationAngle % 360
          document.getElementById('winner-info').innerHTML = `Winner is ${winningSegment.text}!`
        }

        function resetSpinAndPlay(){
          for (let x = 1; x < theWheel.segments.length; x ++) {
            theWheel.segments[x].textStrokeStyle = 'black';
          }
          document.getElementById('winner-info').innerHTML = `Wheel is spinning...`
          theWheel.startAnimation()
        }

        function hexToRgb(hex) {
          var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
          return result ? {
            r: parseInt(result[1], 16),
            g: parseInt(result[2], 16),
            b: parseInt(result[3], 16)
          } : null;
        }

    </script>
    {% if collection.content_set.all.count != 0 %}
      <div class="action-container">
        <button onClick="resetSpinAndPlay()" class="btn submit">Spin</button>
      </div>
    {% endif %}

    <div id="winner-container">
      <p id="winner-info">
        Currently no winner
      </p>
    </div>
    
  </section>
</div>


{% endblock %}

main_app/templates/collections/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/collections/collection-index.css' %}"
/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>Collections</h1>
</section>

<section class="card-container">
  {% if collections.count != 0 %}
    {% for collection in collections %}
      <div class="card">
        <a href="/collections/{{ collection.id }}">
          <div class="card-content">
            <h2 class="card-title">{{ collection.name }}</h2>
            <p><small>{{ collection.description }}</small></p>
          </div>
        </a>
        <a href="{% url 'collections_delete' collection.id %}" class="btn danger collection-delete">X</a>
      </div>
    {% endfor %}
  {% else %}
    <div class="empty-info">
      <p>You have no collections. Create a new collection!</p>
    </div>
  {% endif %}
</section>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}

<section class="logo-container">
  <div class="collection-container">
    <img id="image-home" src="{% static 'images/content.svg' %}" alt="Django Spinner" />
  </div>
</section>
{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}">
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}


{% endblock %}

main_app/templates/main_app/collection_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Collection?</h1>
</div>
<h2>Are you sure you want to delete {{ collection.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'collections_detail' collection.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/contentcollection_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Collection?</h1>
</div>
<h2>Are you sure you want to delete {{ collection.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'collections_index' %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/contentcollection_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Create a new Collection</h1>
</div>
<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Create</button>
</form>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Sign Up</h1>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}